### Question 5
The last question is about the gradient descent of logistic regression.
In the gitlab repository, there is a folder code including the gradient descent algorithm for linear regression. The task here is to write the gradient descent algorithm for the logistic regression. Requirement: the function is called LogisticRegression and is implemented in a class with the following structure.

In [ ]:
def sigmoid(z):
    return # the sigmoid function

class LogisticRegression:
    def __init__(self, M, N, lr = 0.1):
        self.M  = M
        self.N  = N
        self.lr = lr
        self.W  = np.zeros((N, 1))
        self.b  = 0.
        self.scaler = StandardScaler()

    def fit(self, X, y, epoch=2000, visual=False):
        self.scaler.fit(X)
        X = self.scaler.transform(X)

        # perform the gradient descent
        for i in range(epoch):

    def predict(self, X_test):
        X_test = self.scaler.transform(X_test)
        y_hat  = sigmoid(np.dot(X_test, self.W)+self.b)
        return np.where(y_hat>0.5, 1, 0)

    def loss_fcn(self, X, y):
        y_hat  = sigmoid(np.dot(X, self.W) + self.b)
        return -np.sum(y*np.log(y_hat)+(1-y)*np.log(1-y_hat))/self.M
    

## My Answer
### Creating the sigmoid function
Sigmoid Function: First, let’s define the sigmoid function, which is used to transform the linear combination of features into probabilities. The sigmoid function is given by: [$$ \sigma(z) = \frac{1}{1 + e^{-z}} $$]

In [16]:
import numpy as np
from sklearn.preprocessing import StandardScaler

def sigmoid(z):
    return 1 / (1 + np.exp(-z))


### Working on my fit 

In [24]:
class my_LogisticRegression_A:
    # initialization method
    def __init__(self, M, N, lr = 0.1):
        self.M  = M
        self.N  = N
        self.lr = lr
        self.W  = np.zeros(N)#((N, 1))
        self.b  = 0.
        self.scaler = StandardScaler()  
        

    #the fit method
    def fit(self, X, y, epoch=2000, visual=False):
        self.scaler.fit(X)
        X = self.scaler.transform(X)
        #N, M = X.shape

        for i in range(epoch):
            # Compute predictions
            z = np.dot(X, self.W) + self.b
            y_hat = sigmoid(z)

            # Compute gradients
            dW = np.dot(X.T, (y_hat - y)) /self.M #M
            db = np.sum(y_hat - y) / self.M    #M

            # Update weights and bias
            self.W -= self.lr * dW
            self.b -= self.lr * db

            # Optional: Visualize loss during training
            if visual:
                loss = self.loss_fcn(X, y)
                print(f"Epoch {i+1}, Loss: {loss:.4f}")

    # the predict and the loss fuction methods

    def predict(self, X_test):
        X_test = self.scaler.transform(X_test)
        y_hat  = sigmoid(np.dot(X_test, self.W)+self.b)
        return np.where(y_hat>0.5, 1, 0)

    def loss_fcn(self, X, y):
        y_hat  = sigmoid(np.dot(X, self.W) + self.b)
        return -np.sum(y*np.log(y_hat)+(1-y)*np.log(1-y_hat))/self.M    

# Testing my code using some random data

In [25]:
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LogisticRegression

# Example data (replace with your actual data)
X = np.random.rand(100, 4)  # Features
y = np.random.randint(0, 2, size=100)  # Binary labels (0 or 1)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Reshape y_train and y_test using ravel()
y_train = y_train.ravel()
y_test = y_test.ravel()
print(y_train.shape,y_test.shape)
# Create and fit a logistic regression model
mdl = my_LogisticRegression_A(M=X_train.shape[0],N=X_train.shape[1])
mdl.fit(X_train, y_train)

# Make predictions
y_pred0 = mdl.predict(X_test)

# Evaluate the model (e.g., accuracy, precision, recall, etc.)
# ...

# Note: You don't need to reshape y_pred; it will have the correct shape automatically.
print(y_pred0)

(80,) (20,)
[1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 0]


### This might be anoter way of coding it 

In [13]:
import numpy as np

class my_LogisticRegression_B:
    def __init__(self, learning_rate=0.01, num_iterations=1000):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        M, N = X.shape
        self.W = np.zeros(N)
        self.b = 0

        for _ in range(self.num_iterations):
            z = np.dot(X, self.W) + self.b
            y_hat = self.sigmoid(z)

            # Compute the cross-entropy loss
            loss = -np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat)) / M

            # Compute gradients
            dW = np.dot(X.T, (y_hat - y)) / M
            db = np.sum(y_hat - y) / M

            # Update weights and bias
            self.W -= self.learning_rate * dW
            self.b -= self.learning_rate * db

    def predict(self, X):
        z = np.dot(X, self.W) + self.b
        y_pred = self.sigmoid(z)
        return np.where(y_pred > 0.5, 1, 0)

# Example usage
X = np.random.rand(100, 2)  # Features
y = np.random.randint(0, 2, size=100)  # Binary labels (0 or 1)

model_B = my_LogisticRegression_B()
model_B.fit(X, y)
print(X.shape,y.shape)

# Make predictions
y_pred = model_B.predict(X)
print(y_pred)

(100, 2) (100,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


### Testing the code with random data

In [11]:
import numpy as np
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LogisticRegression

# Example data (replace with your actual data)
X = np.random.rand(100, 4)  # Features
y = np.random.randint(0, 2, size=100)  # Binary labels (0 or 1)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Reshape y_train and y_test using ravel()
y_train = y_train.ravel()
y_test = y_test.ravel()
print(y_train.shape,y_test.shape)
# Create and fit a logistic regression model
clf = my_LogisticRegression_B()
clf.fit(X_train, y_train)

# Make predictions
y_pred1 = clf.predict(X_test)

# Evaluate the model (e.g., accuracy, precision, recall, etc.)
# ...

# Note: You don't need to reshape y_pred; it will have the correct shape automatically.
print(y_pred1)

(80,) (20,)
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


#### This is one key error that i was a game changer in my code.

In [22]:
N=20
np.zeros(N)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [23]:
np.zeros((N, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])